name: Coverage with CodeClimate
on: [push, pull_request]
jobs:
  codeclimate-report:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - run: go build
    - uses: paambaati/codeclimate-action@v3.2.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        coverageCommand: go test ./... -coverprofile c.out
        prefix: github.com/atony2099/filesrv 